language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - service/travis

before_install:
  - sudo apt-get install php5-dev
  - wget https://github.com/phpredis/phpredis/archive/develop.zip && unzip develop.zip && cd phpredis-develop
  - phpize
  - ./configure
  - make
  - sudo make install
  - sudo echo 'extension=redis.so' > /etc/php5/conf.d/redis.ini

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml.dist --coverage-text