language: php

php:
  - 5.6

branches:
  only:
    - service/travis

addons:
  apt:
    packages:
    - php5-dev
    - php5-redis

before_install:
  - wget https://github.com/phpredis/phpredis/archive/develop.zip && unzip develop.zip && cd phpredis-develop
  - phpize
  - ./configure
  - make
  - sudo make install
  - sudo mkdir -p /etc/php5/cli/conf.d/
  - echo 'extension='`pwd`'/modules/redis.so' | sudo tee /etc/php5/cli/conf.d/redis.ini > /dev/null
  - cd ../

install:
  - composer install --no-dev

services:
  - redis-server

script: phpunit --configuration phpunit.xml.dist --coverage-text