language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - feature/raqualizer

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml.dist --testsuite 'Mufuphlex Raqualizer Test Suite' --coverage-text